services:
  kafka-kraft-1:
    image: docker.io/bitnami/kafka:3.7
    container_name: kafka-kraft-1
    hostname: kafka-kraft-1
    ports:
      - "19091:9092"
    environment:
      # KRaft settings
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_KRAFT_CLUSTER_ID: 'abcdefgh12345678'

      # Listeners
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENERS: BROKER://kafka-kraft-1:9099,CONTROLLER://kafka-kraft-1:9093,EXTERNAL://0.0.0.0:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: BROKER://kafka-kraft-1:9099,EXTERNAL://10.6.200.96:19091
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT,EXTERNAL:PLAINTEXT

      # Topic/offset config
      KAFKA_CFG_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_CFG_LOG_RETENTION_HOURS: 168
      KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: true

      # Logs
      KAFKA_CFG_LOG4J_ROOT_LOGLEVEL: DEBUG
      KAFKA_CFG_LOG4J_LOGGERS: "kraft=DEBUG"
    networks:
      - hieuht1_kafka_network
