services:
  kafka-kraft-1:
    image: apache/kafka:4.1.2
    container_name: kafka-kraft-1
    hostname: kafka-kraft-1
    ports:
      - "19091:9092"
    environment:
      # KRaft settings
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-kraft-1:9093,2@kafka-kraft-2:9093,3@kafka-kraft-3:9093
      CLUSTER_ID: 'abcdefgh12345678'

      # Listeners
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENERS: BROKER://kafka-kraft-1:9099,CONTROLLER://kafka-kraft-1:9093,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: BROKER://kafka-kraft-1:9099,EXTERNAL://localhost:19091
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT,EXTERNAL:PLAINTEXT

      # Topic/offset config
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: false
    networks:
      - hieuht1_kafka_network
