server:
  port: ${SERVER_PORT:0}

spring:
  application:
    name: stream-service
  main:
    web-application-type: REACTIVE
  webflux:
    base-path: /api/streams
  flyway:
    enabled: true
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:streaming-platform}
    user: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:123456a}
    schemas: stream
    locations: classpath:db/migration
  r2dbc:
    url: "r2dbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:streaming-platform}?options=search_path%3Dstream"
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:123456a}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
    instance-id: "${streaming.service.instance-id}"

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

streaming:
  service:
    instance-id: "${random.uuid}"
  jwt:
    issuer: ${JWT_ISSUER:https://auth.streaming.local}
    hmac-secret: ${JWT_HMAC_SECRET:MNH6CwQ7H4xAf69hpn0sc2Rn+wxT/d+I9QWELikQqgM=}
